# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  profile: chill
  high_level_summary: true

  path_instructions:
    - path: "apps/demo/**"
      instructions: >
        apps/demo directory contains a demo application for testing purposes.
        It can be used as a reference for SDK usage examples.

    # ─────────────────────────────────────────────────────────
    # DOCS
    # ─────────────────────────────────────────────────────────

    # Human-editable documentation content
    - path: "docs/enclave/**"
      instructions: >
        This folder contains all the human-editable Mintlify documentation (MDX files).
        It includes sections like getting-started, concepts, core-libraries, enclavejs,
        guides, examples, troubleshooting, api-reference, and snippets.
        As a reviewer:
        - Ensure documentation is clear, accurate, and matches the current SDK APIs.
        - Check for broken links or references to non-existent pages.
        - Verify code examples are correct and follow best practices.

    # Mintlify navigation config
    - path: "docs/docs.json"
      instructions: >
        Mintlify navigation configuration.
        Structure:
        - dropdowns[].dropdown == "Documentation":
          - Contains groups for different documentation sections.
          - Paths reference content under docs/enclave/ (e.g. "enclave/getting-started/welcome").
        Review guidelines:
        - Ensure navigation paths match actual files in docs/enclave/.
        - Verify group structure is logical and well-organized.

    # Generic docs catch-all (for anything not covered above)
    - path: "docs/**"
      instructions: >
        Repository documentation for the SDK, using MDX and hosted by Mintlify.
        See more specific rules for:
        - docs/enclave/** (human-editable documentation content)
        - docs/docs.json (Mintlify navigation)

    # SDK libs
    - path: "libs/**"
      instructions: >
        Contains publishable SDK libraries.
        Review for API correctness, breaking changes, and consistency with docs.
        When public APIs change, ensure there is a matching documentation update
        under docs/enclave/**.

  path_filters:
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/coverage/**"
    - "!**/.next/**"
    - "!**/.nuxt/**"
    - "!**/.svelte-kit/**"
    - "!**/.turbo/**"
    - "!**/.swc/**"
    - "!**/.parcel-cache/**"
    - "!**/node_modules/**"
    - "!**/.yarn/**"
    - "!**/.pnpm-store/**"
    - "!**/*.min.{js,css}"
    - "!**/*.map"
    - "!**/public/**"
    - "!**/*.svg"
    - "!**/*lock*.{json,yaml,yml}"
